apiVersion: v1
kind: ServiceAccount
metadata:
  name: tailscale
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tailscale
rules:
- apiGroups: [""] 
  resources: ["secrets"]
  verbs: ["create"]
- apiGroups: [""] 
  resourceNames: ["tailscale-auth"]
  resources: ["secrets"]
  verbs: ["get", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tailscale
subjects:
- kind: ServiceAccount
  name: "tailscale"
roleRef:
  kind: Role
  name: tailscale
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: fastchat-proxy
spec:
  serviceName: fastchat-proxy
  replicas: 1
  selector:
    matchLabels:
      app: fastchat-proxy
  template:
    metadata:
      labels:
        app: fastchat-proxy
    spec:
      serviceAccountName: tailscale
      initContainers:
        - name: sysctler
          image: busybox
          securityContext:
            privileged: true
          command: ["/bin/sh"]
          args: ["-c", "sysctl -w net.ipv4.ip_forward=1 net.ipv6.conf.all.forwarding=1"]
          resources:
            requests:
              cpu: 1m
              memory: 1Mi
      containers:
        - name: fastchat-proxy
          imagePullPolicy: Always
          image: "ghcr.io/tailscale/tailscale:latest"
          env: 
            - name: TS_KUBE_SECRET
              value: "tailscale-auth"
            - name: TS_USERSPACE
              value: "false"
            - name: TS_DEST_IP
              value: 
            - name: TS_AUTH_ONCE
              value: "true"
          securityContext:
            capabilities:
              add: ["NET_ADMIN"]
---
apiVersion: v1
kind: Secret
metadata:
  name: tailscale-auth
stringData:
  TS_AUTHKEY: tskey-0123456789abcdef